# Generated by Django 5.2.7 on 2026-03-16 15:38

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CryptoAsset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Full name (e.g., Bitcoin)', max_length=50, unique=True)),
                ('symbol', models.CharField(help_text='Symbol (e.g., BTC)', max_length=10, unique=True)),
                ('icon', models.CharField(default='₿', help_text='Icon character to display', max_length=10)),
                ('color', models.CharField(default='#f7931a', help_text='Hex color code', max_length=20)),
                ('current_price', models.DecimalField(decimal_places=8, help_text='Current market price in USD', max_digits=20, validators=[django.core.validators.MinValueValidator(0)])),
                ('base_price', models.DecimalField(decimal_places=8, help_text='Base price for calculating percentage change', max_digits=20, validators=[django.core.validators.MinValueValidator(0)])),
                ('order', models.IntegerField(default=0, help_text='Display order (lower numbers appear first)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Crypto Asset',
                'verbose_name_plural': 'Crypto Assets',
                'ordering': ['order', 'name'],
            },
        ),
    ]
