# Generated by Django 5.2.7 on 2026-03-16 21:24

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ReceiveTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('wallet_address', models.CharField(help_text='Wallet address used for receiving', max_length=255)),
                ('proof_of_transfer', models.FileField(help_text='Upload proof of transfer file', upload_to='proof_transfers/')),
                ('amount', models.DecimalField(blank=True, decimal_places=8, help_text='Amount received (filled by admin)', max_digits=20, null=True, validators=[django.core.validators.MinValueValidator(0)])),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('confirmed', 'Confirmed'), ('rejected', 'Rejected')], default='pending', max_length=20)),
                ('admin_notes', models.TextField(blank=True, help_text='Admin notes about this transaction')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('crypto_asset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='receive_transactions', to='app.cryptoasset')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='receive_transactions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Receive Transaction',
                'verbose_name_plural': 'Receive Transactions',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='UserWallet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('balance', models.DecimalField(decimal_places=8, default=0, help_text="User's balance for this cryptocurrency", max_digits=20, validators=[django.core.validators.MinValueValidator(0)])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('crypto_asset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_wallets', to='app.cryptoasset')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='wallets', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'User Wallet',
                'verbose_name_plural': 'User Wallets',
                'ordering': ['crypto_asset__order'],
                'unique_together': {('user', 'crypto_asset')},
            },
        ),
    ]
