# Generated by Django 5.2.7 on 2026-03-16 21:45

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_receivetransaction_userwallet'),
    ]

    operations = [
        migrations.AlterField(
            model_name='receivetransaction',
            name='amount',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Amount in USD (filled by admin)', max_digits=20, null=True, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='userwallet',
            name='balance',
            field=models.DecimalField(decimal_places=2, default=0, help_text="User's balance in USD for this cryptocurrency", max_digits=20, validators=[django.core.validators.MinValueValidator(0)]),
        ),
    ]
