# Generated by Django 5.2.7 on 2026-03-16 22:06

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_alter_receivetransaction_amount_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SwapTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('from_amount_usd', models.DecimalField(decimal_places=2, help_text='Amount swapped FROM in USD', max_digits=20, validators=[django.core.validators.MinValueValidator(0)])),
                ('to_amount_usd', models.DecimalField(decimal_places=2, help_text='Amount received TO in USD', max_digits=20, validators=[django.core.validators.MinValueValidator(0)])),
                ('from_price', models.DecimalField(decimal_places=8, help_text='Price of FROM crypto at swap time', max_digits=20)),
                ('to_price', models.DecimalField(decimal_places=8, help_text='Price of TO crypto at swap time', max_digits=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('from_crypto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='swaps_from', to='app.cryptoasset')),
                ('to_crypto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='swaps_to', to='app.cryptoasset')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='swap_transactions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Swap Transaction',
                'verbose_name_plural': 'Swap Transactions',
                'ordering': ['-created_at'],
            },
        ),
    ]
