# Generated by Django 5.2.7 on 2026-03-16 22:20

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_swaptransaction'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SellTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount_to_sell', models.DecimalField(decimal_places=2, help_text='Amount user wants to sell in USD', max_digits=20, validators=[django.core.validators.MinValueValidator(0)])),
                ('proof_of_transfer', models.FileField(help_text='Upload proof of crypto sent', upload_to='sell_proofs/')),
                ('amount', models.DecimalField(blank=True, decimal_places=2, help_text='Amount paid to user in USD (filled by admin)', max_digits=20, null=True, validators=[django.core.validators.MinValueValidator(0)])),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('confirmed', 'Confirmed'), ('rejected', 'Rejected')], default='pending', max_length=20)),
                ('admin_notes', models.TextField(blank=True, help_text='Admin notes about this transaction')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('crypto_asset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sell_transactions', to='app.cryptoasset')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sell_transactions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Sell Transaction',
                'verbose_name_plural': 'Sell Transactions',
                'ordering': ['-created_at'],
            },
        ),
    ]
