# Generated by Django 5.2.7 on 2026-03-20 13:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_notification'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bio', models.TextField(blank=True, help_text='User biography', null=True)),
                ('profile_image', models.ImageField(blank=True, help_text='Profile picture', null=True, upload_to='profile_images/')),
                ('email_transactions', models.BooleanField(default=True, help_text='Receive transaction notifications')),
                ('email_security', models.BooleanField(default=True, help_text='Receive security alerts')),
                ('email_marketing', models.BooleanField(default=False, help_text='Receive marketing emails')),
                ('two_factor_enabled', models.BooleanField(default=False, help_text='Two-factor authentication enabled')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'User Profile',
                'verbose_name_plural': 'User Profiles',
            },
        ),
    ]
