# Generated by Django 5.2.7 on 2026-03-20 16:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_userprofile'),
    ]

    operations = [
        migrations.AddField(
            model_name='cryptoasset',
            name='icon_url',
            field=models.URLField(blank=True, help_text='URL to coin logo image', max_length=500, null=True),
        ),
    ]
