# Generated by Django 5.2.7 on 2026-03-23 16:03

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_cryptoasset_icon_url'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserHolding',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('balance', models.DecimalField(decimal_places=8, default=0, help_text='Amount of cryptocurrency held', max_digits=20, validators=[django.core.validators.MinValueValidator(0)])),
                ('average_buy_price', models.DecimalField(decimal_places=8, default=0, help_text='Average price at which this asset was purchased', max_digits=20, validators=[django.core.validators.MinValueValidator(0)])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('crypto_asset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_holdings', to='app.cryptoasset')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='holdings', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'User Holding',
                'verbose_name_plural': 'User Holdings',
                'ordering': ['-balance'],
                'unique_together': {('user', 'crypto_asset')},
            },
        ),
    ]
