# Generated by Django 5.2.7 on 2026-03-25 16:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_contactmessage'),
    ]

    operations = [
        migrations.AddField(
            model_name='cryptoasset',
            name='asset_type',
            field=models.CharField(choices=[('crypto', 'Cryptocurrency'), ('stock', 'Stock (xStocks)')], default='crypto', help_text='Type of asset', max_length=10),
        ),
        migrations.AddField(
            model_name='cryptoasset',
            name='is_in_watchlist',
            field=models.BooleanField(default=True, help_text='Show in watchlist'),
        ),
    ]
