# Generated by Django 5.2.7 on 2026-03-31 12:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0011_cryptoasset_asset_type_cryptoasset_is_in_watchlist'),
    ]

    operations = [
        migrations.AddField(
            model_name='cryptoasset',
            name='receive_wallet_address',
            field=models.CharField(blank=True, help_text='Wallet address for receiving this crypto (for BTC, XRP, XLM, HBAR only)', max_length=255, null=True),
        ),
    ]
