# Generated by Django 5.2.7 on 2026-03-31 21:33

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0012_cryptoasset_receive_wallet_address'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserPriceOverride',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('xrp_custom_price', models.DecimalField(blank=True, decimal_places=8, help_text='Custom XRP price for this user (overrides global XRP price site-wide for this user only)', max_digits=20, null=True, validators=[django.core.validators.MinValueValidator(0)])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='xrp_price_override', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'User XRP Price Override',
                'verbose_name_plural': 'User XRP Price Overrides',
            },
        ),
    ]
