# Generated by Django 5.2.7 on 2026-04-01 13:33

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0013_userpriceoverride'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='userwallet',
            options={'ordering': ['user__username', 'crypto_asset__order'], 'verbose_name': 'User Wallet', 'verbose_name_plural': 'User Wallets'},
        ),
        migrations.AddField(
            model_name='userprofile',
            name='wallet_balance',
            field=models.DecimalField(decimal_places=2, default=0, help_text="User's main wallet balance in USD (shown in dashboard)", max_digits=20, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='userwallet',
            name='balance',
            field=models.DecimalField(decimal_places=8, default=0, max_digits=20, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='userwallet',
            name='crypto_asset',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.cryptoasset'),
        ),
    ]
