# Generated by Django 5.2.7 on 2026-04-10 10:56

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0015_alter_userwallet_balance'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='userpriceoverride',
            options={'verbose_name': 'User Price Override', 'verbose_name_plural': 'User Price Overrides'},
        ),
        migrations.AddField(
            model_name='userpriceoverride',
            name='tslax_custom_price',
            field=models.DecimalField(blank=True, decimal_places=8, help_text='Custom TSLAx price for this user (overrides global TSLAx price site-wide for this user only)', max_digits=20, null=True, validators=[django.core.validators.MinValueValidator(0)]),
        ),
    ]
